### PR TITLE
SetHullDuck

### PR DESCRIPTION
**Pull request by Jonpopnycorn**
Since the hull was fixed, small props like the boots ph_minecraft_awakening to be blocked off from going under the tables

This will allow small props to crouch to get to certain places.

### CODE REVIEW

**Comment by Vinzuerio** [comment]
Need to test on other maps too btw, I noticed that some maps has weird hull while ducking so it just let passes the player through (the most notable one is short vent system)

Once the test did the same thing like in ph_minecraft_awakening map, I'll merge the pull the commit

**Comment by Jonpopnycorn** [comment]
What kind of weird hull while ducking?

**Comment by Jonpopnycorn** [comment]
Updated this pull with a fix for the Props Playermodel shadow bug #27

**Comment by Vinzuerio** [comment]
Done, i'll keep this remain open if there's any further problem persists.

**Pull request merged**
