### PR TITLE
Modify cl_autotaunt.lua

### PR DESCRIPTION
**Pull request by lucas2107**
Prevent auto taunt & timer display for Hunters.

### CODE REVIEW

**Comment by lucas2107** [comment]
#30

**Comment by Thundernerd** [comment]
Not sure if this is the best way to fix it. Isn't there a hook to listen for a team switch? That's what I would look for and then on team switch make sure to check again. Just personal preference though.

**Comment by lucas2107** [comment]
That's working for me ^^ I know it's not the best way to fix but I'm not a developper I've just tried something to fix my problem

**Comment by Vinzuerio** [comment]
@Thundernerd [OnPlayerChangedTeam ?](http://wiki.garrysmod.com/page/GM/OnPlayerChangedTeam) Server side only, need some networking stuff again for that

Also, FYI that "Player" prop will die silently. (which this will call PlayerSilentDeath instead PlayerDeath)
Use [OnTakeDamage](https://github.com/Vinzuerio/ph-enhanced/blob/master/gamemodes/prop_hunt/entities/entities/ph_prop/init.lua) instead for better controlling

**Comment by Vinzuerio** [comment]
I have to re-clean up the code just to make sure the code isn't messed up before committing the v15 patch update in the future

**Pull request closed without merging**
